// frontend-replit/artifacts/svvy/src/components/svvy/SubagentCard.tsx
import { cn } from "@/lib/utils";
import { StatusDot } from "./StatusBadge";
import { ModelBadge } from "./ModelBadge";
import { Zap, Search, Code2, Eye, Workflow, Bot } from "lucide-react";
import { usePanes } from "@/hooks/usePanes";
import type { SubagentItem, AgentType } from "@/data/mock";

interface SubagentCardProps {
  agent: SubagentItem;
  className?: string;
  expandable?: boolean;
}

const agentConfig: Record<AgentType, { icon: React.ElementType; label: string; color: string }> = {
  orchestrator: { icon: Bot, label: "orchestrator", color: "text-orange-400" },
  quick: { icon: Zap, label: "quick", color: "text-yellow-400" },
  explorer: { icon: Search, label: "explorer", color: "text-blue-400" },
  implementer: { icon: Code2, label: "implementer", color: "text-purple-400" },
  reviewer: { icon: Eye, label: "reviewer", color: "text-cyan-400" },
  "workflow-writer": { icon: Workflow, label: "workflow-writer", color: "text-slate-400" },
};

export function SubagentCard({ agent, className, expandable = true }: SubagentCardProps) {
  const { openPane } = usePanes();
  const config = agentConfig[agent.type] || agentConfig.orchestrator;
  const Icon = config.icon;

  const handleClick = () => {
    if (!expandable) return;
    openPane("subagent", agent, `${config.label}: ${agent.headline.slice(0, 32)}…`);
  };

  return (
    <div
      className={cn(
        "flex items-center gap-2 px-2 py-1.5 rounded bg-muted/40 border border-border/50",
        expandable && "hover:bg-muted/70 transition-colors cursor-pointer",
        className
      )}
      onClick={handleClick}
      role={expandable ? "button" : undefined}
      tabIndex={expandable ? 0 : undefined}
      onKeyDown={e => e.key === "Enter" && handleClick()}
      data-testid={`subagent-card-${agent.id}`}
    >
      <Icon className={cn("w-3 h-3 flex-shrink-0", config.color)} />
      <span className={cn("font-mono text-[10px] flex-shrink-0", config.color)}>{config.label}</span>
      <span className="text-[11px] text-foreground/80 flex-1 truncate">{agent.headline}</span>

      <div className="flex items-center gap-1.5 flex-shrink-0">
        <StatusDot status={agent.status} />
        {agent.tokens && (
          <span className="font-mono text-[9px] text-muted-foreground">{(agent.tokens / 1000).toFixed(1)}k</span>
        )}
        <ModelBadge model={agent.model} size="xs" />
        {expandable && (
          <span className="font-mono text-[8px] text-muted-foreground/40">→</span>
        )}
      </div>
    </div>
  );
}

// src/mainview/reference-cards/SubagentCard.svelte
<script lang="ts" module>
  import type { ReferenceStatus } from "./StatusBadge.svelte";

  export type ReferenceAgentType =
    | "orchestrator"
    | "handler-thread"
    | "workflow-task-agent"
    | "dumb"
    | "explorer"
    | "implementer"
    | "reviewer"
    | "workflow-writer";

  export type ReferenceSubagent = {
    id: string;
    type: ReferenceAgentType;
    headline: string;
    status: ReferenceStatus;
    model: string;
    tokens?: number;
  };
</script>

<script lang="ts">
  import BotIcon from "@lucide/svelte/icons/bot";
  import Code2Icon from "@lucide/svelte/icons/code-2";
  import EyeIcon from "@lucide/svelte/icons/eye";
  import SearchIcon from "@lucide/svelte/icons/search";
  import WorkflowIcon from "@lucide/svelte/icons/workflow";
  import ZapIcon from "@lucide/svelte/icons/zap";
  import ModelBadge from "./ModelBadge.svelte";
  import StatusBadge from "./StatusBadge.svelte";

  type Props = {
    agent: ReferenceSubagent;
    class?: string;
    expandable?: boolean;
    onclick?: (agent: ReferenceSubagent) => void;
  };

  let { agent, class: className = "", expandable = true, onclick }: Props = $props();

  const agentConfig = {
    orchestrator: { icon: BotIcon, label: "orchestrator", tone: "orange" },
    "handler-thread": { icon: BotIcon, label: "handler", tone: "blue" },
    "workflow-task-agent": { icon: WorkflowIcon, label: "task-agent", tone: "cyan" },
    dumb: { icon: ZapIcon, label: "dumb", tone: "yellow" },
    explorer: { icon: SearchIcon, label: "explorer", tone: "blue" },
    implementer: { icon: Code2Icon, label: "implementer", tone: "purple" },
    reviewer: { icon: EyeIcon, label: "reviewer", tone: "cyan" },
    "workflow-writer": { icon: WorkflowIcon, label: "workflow-writer", tone: "muted" },
  } as const;

  const config = $derived(agentConfig[agent.type] ?? agentConfig["handler-thread"]);
  const Icon = $derived(config.icon);
  const tokenLabel = $derived(agent.tokens ? `${(agent.tokens / 1000).toFixed(1)}k` : null);

  function open() {
    if (!expandable) return;
    onclick?.(agent);
  }

  function keydown(event: KeyboardEvent) {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      open();
    }
  }
</script>

<button
  type="button"
  class={`flex items-center gap-2 px-2 py-1.5 rounded-md bg-muted/40 border border-border/50 text-left min-w-0 ${expandable ? "hover:bg-muted/70 transition-colors cursor-pointer group focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" : ""} ${className}`.trim()}
  aria-disabled={!expandable}
  onclick={open}
  onkeydown={keydown}
  data-testid={`subagent-card-${agent.id}`}
>
  <Icon class="w-3.5 h-3.5 text-muted-foreground group-hover:text-foreground transition-colors flex-shrink-0" strokeWidth={2.1} />

  <div class="flex-1 min-w-0 flex items-center gap-1.5">
    <span class="text-[11px] font-medium text-foreground truncate">{agent.headline}</span>
    <span class="text-[9px] font-mono text-muted-foreground/60 uppercase tracking-wider flex-shrink-0">{config.label}</span>
  </div>

  <div class="flex items-center gap-1.5 flex-shrink-0">
    <StatusBadge status={agent.status} dotOnly size="xs" />
    {#if tokenLabel}
      <span class="text-[9px] font-mono text-muted-foreground/60">{tokenLabel}</span>
    {/if}
    <ModelBadge model={agent.model} size="xs" />
    {#if expandable}
      <span class="text-[9px] font-mono text-muted-foreground/40" aria-hidden="true">-&gt;</span>
    {/if}
  </div>
</button>
