// src/mainview/reference-cards/EpisodeCard.svelte
<script lang="ts" module>
  import type { ReferenceArtifact } from "./ArtifactChip.svelte";

  export type ReferenceEpisode = {
    id: string;
    title: string;
    summary: string;
    thread?: string;
    verified?: boolean;
    artifacts?: ReferenceArtifact[];
  };
</script>

<script lang="ts">
  import AlertTriangleIcon from "@lucide/svelte/icons/alert-triangle";
  import BookOpenIcon from "@lucide/svelte/icons/book-open";
  import CheckCircle2Icon from "@lucide/svelte/icons/check-circle-2";
  import ArtifactChip from "./ArtifactChip.svelte";

  type Props = {
    episode: ReferenceEpisode;
    class?: string;
    onartifactopen?: (artifact: ReferenceArtifact) => void;
  };

  let { episode, class: className = "", onartifactopen }: Props = $props();
</script>

<article class={`reference-episode-card ${className}`.trim()} data-testid={`episode-card-${episode.id}`}>
  <BookOpenIcon size={14} strokeWidth={2} class="episode-icon" />
  <div class="episode-copy">
    <header>
      <strong>{episode.title}</strong>
      <span class:verified={episode.verified}>
        {#if episode.verified}
          <CheckCircle2Icon size={11} strokeWidth={2} />
          verified
        {:else}
          <AlertTriangleIcon size={11} strokeWidth={2} />
          review
        {/if}
      </span>
    </header>
    <p>{episode.summary}</p>
    {#if episode.artifacts?.length}
      <div class="episode-artifacts">
        {#each episode.artifacts as artifact (artifact.id)}
          <ArtifactChip name={artifact.name} type={artifact.type} {artifact} onclick={onartifactopen} />
        {/each}
      </div>
    {/if}
    {#if episode.thread}
      <footer><small>Thread:</small><span>{episode.thread}</span></footer>
    {/if}
  </div>
</article>

<style>
  .reference-episode-card {
    display: flex;
    align-items: flex-start;
    gap: 0.56rem;
    padding: 0.68rem 0.78rem;
    border: 1px solid var(--ui-border-soft);
    border-radius: var(--ui-radius-md);
    background: var(--ui-surface);
  }

  .episode-icon {
    flex: 0 0 auto;
    margin-top: 0.12rem;
    color: var(--ui-text-tertiary);
  }

  .episode-copy {
    display: grid;
    gap: 0.42rem;
    min-width: 0;
    flex: 1;
  }

  header,
  header span,
  footer,
  .episode-artifacts {
    display: flex;
    align-items: center;
    min-width: 0;
  }

  header {
    justify-content: space-between;
    gap: 0.6rem;
  }

  strong {
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    color: var(--ui-text-primary);
    font-size: 0.74rem;
    font-weight: 650;
  }

  header span {
    gap: 0.22rem;
    flex: 0 0 auto;
    padding: 0.08rem 0.36rem;
    border: 1px solid color-mix(in oklab, var(--ui-warning) 25%, var(--ui-border-soft));
    border-radius: var(--ui-radius-sm);
    background: var(--ui-warning-soft);
    color: color-mix(in oklab, var(--ui-warning) 82%, var(--ui-text-primary));
    font-family: var(--font-mono);
    font-size: 0.56rem;
  }

  header span.verified {
    border-color: color-mix(in oklab, var(--ui-success) 25%, var(--ui-border-soft));
    background: var(--ui-success-soft);
    color: color-mix(in oklab, var(--ui-success) 78%, var(--ui-text-primary));
  }

  p {
    margin: 0;
    color: var(--ui-text-secondary);
    font-size: 0.68rem;
    line-height: 1.48;
  }

  .episode-artifacts {
    gap: 0.3rem;
    flex-wrap: wrap;
  }

  footer {
    gap: 0.28rem;
    color: var(--ui-text-tertiary);
    font-size: 0.58rem;
  }

  footer small,
  footer span {
    font-family: var(--font-mono);
  }
</style>

// frontend-replit/artifacts/svvy/src/components/svvy/EpisodeCard.tsx
import { cn } from "@/lib/utils";
import { BookOpen, CheckCircle2, AlertTriangle } from "lucide-react";
import { ArtifactChip } from "./ArtifactChip";
import type { Episode } from "@/data/mock";

interface EpisodeCardProps {
  episode: Episode;
  className?: string;
}

export function EpisodeCard({ episode, className }: EpisodeCardProps) {
  return (
    <div
      className={cn(
        "border border-border rounded bg-card px-3 py-2.5",
        className
      )}
      data-testid={`episode-card-${episode.id}`}
    >
      <div className="flex items-start gap-2 mb-2">
        <BookOpen className="w-3.5 h-3.5 text-muted-foreground mt-0.5 flex-shrink-0" />
        <div className="flex-1 min-w-0">
          <div className="flex items-start justify-between gap-2">
            <h4 className="text-[12px] font-medium text-foreground leading-tight">{episode.title}</h4>
            <div className="flex-shrink-0">
              {episode.verified ? (
                <span className="flex items-center gap-1 text-[10px] text-emerald-400 font-mono border border-emerald-500/20 bg-emerald-500/8 rounded px-1.5 py-0.5">
                  <CheckCircle2 className="w-2.5 h-2.5" />
                  verified
                </span>
              ) : (
                <span className="flex items-center gap-1 text-[10px] text-amber-400 font-mono border border-amber-500/20 bg-amber-500/8 rounded px-1.5 py-0.5">
                  <AlertTriangle className="w-2.5 h-2.5" />
                  review
                </span>
              )}
            </div>
          </div>
          <p className="text-[11px] text-muted-foreground mt-1 leading-relaxed line-clamp-2">{episode.summary}</p>
        </div>
      </div>

      {episode.artifacts.length > 0 && (
        <div className="flex flex-wrap gap-1 mb-2 pl-5">
          {episode.artifacts.map(a => (
            <ArtifactChip
              key={a.id}
              name={a.name}
              type={a.type}
              artifact={a}
            />
          ))}
        </div>
      )}

      <div className="pl-5 flex items-center gap-1.5">
        <span className="text-[10px] text-muted-foreground">Thread:</span>
        <button className="text-[10px] text-muted-foreground hover:text-foreground transition-colors underline underline-offset-2">
          {episode.thread}
        </button>
      </div>
    </div>
  );
}
