// src/mainview/transcript-cards/WaitingCard.svelte
<script lang="ts">
  import ClockIcon from "@lucide/svelte/icons/clock";

  type Props = {
    question: string;
    context?: string;
    class?: string;
    onreply?: (text: string) => void;
  };

  let { question, context, class: className = "", onreply }: Props = $props();
  let reply = $state("");

  function send() {
    const text = reply.trim();
    if (!text) return;
    onreply?.(text);
    reply = "";
  }
</script>

<article class={`reference-waiting-card ${className}`.trim()} data-testid="waiting-card">
  <header>
    <span class="pulse-dot"></span>
    <ClockIcon size={14} strokeWidth={2} />
    <strong>Waiting for input</strong>
  </header>
  <div class="waiting-body">
    {#if context}<p class="context">{context}</p>{/if}
    <p>{question}</p>
    {#if onreply}
      <div class="reply-row">
        <input
          bind:value={reply}
          placeholder="Type your response..."
          onkeydown={(event) => {
            if (event.key === "Enter") send();
          }}
        />
        <button type="button" disabled={!reply.trim()} onclick={send}>Reply</button>
      </div>
    {/if}
  </div>
</article>

<style>
  .reference-waiting-card {
    border: 1px solid color-mix(in oklab, var(--ui-status-waiting) 34%, var(--ui-border-soft));
    border-radius: var(--ui-radius-md);
    background: color-mix(in oklab, var(--ui-surface) 94%, var(--ui-status-waiting-soft));
    overflow: hidden;
  }

  header,
  .reply-row {
    display: flex;
    align-items: center;
  }

  header {
    gap: 0.45rem;
    padding: 0.62rem 0.72rem;
    border-bottom: 1px solid var(--ui-border-soft);
    color: color-mix(in oklab, var(--ui-status-waiting) 84%, var(--ui-text-primary));
  }

  .pulse-dot {
    width: 0.42rem;
    height: 0.42rem;
    border-radius: 999px;
    background: var(--ui-status-waiting);
    animation: pulse-dot 1.4s ease-in-out infinite;
  }

  strong {
    font-size: var(--text-sm);
    font-weight: 600;
  }

  .waiting-body {
    display: grid;
    gap: 0.62rem;
    padding: 0.7rem 0.78rem;
  }

  p {
    margin: 0;
    color: var(--ui-text-primary);
    font-size: var(--text-sm);
    line-height: 1.5;
  }

  .context {
    color: var(--ui-text-secondary);
    font-size: var(--text-xs);
  }

  .reply-row {
    gap: 0.45rem;
  }

  input {
    flex: 1;
    min-width: 0;
    min-height: 1.8rem;
    padding: 0.28rem 0.52rem;
    border: 1px solid var(--ui-border-soft);
    border-radius: var(--ui-radius-sm);
    background: var(--ui-surface-subtle);
    color: var(--ui-text-primary);
    font: inherit;
    font-size: var(--text-xs);
  }

  button {
    position: relative;
    min-height: 1.8rem;
    padding: 0.24rem 0.68rem;
    border: 1px solid var(--ui-accent);
    border-radius: var(--ui-radius-sm);
    background: var(--ui-accent);
    color: var(--ui-accent-ink);
    font-size: var(--text-xs);
    font-weight: 600;
    cursor: pointer;
  }

  button::before {
    content: "";
    position: absolute;
    inset: 50% auto auto 50%;
    width: max(100%, 1.9rem);
    height: max(100%, 1.9rem);
    transform: translate(-50%, -50%);
    border-radius: inherit;
  }

  input:focus-visible,
  button:focus-visible {
    outline: none;
    box-shadow: var(--ui-focus-ring);
  }

  button:disabled {
    border-color: var(--ui-border-soft);
    background: var(--ui-surface-muted);
    color: var(--ui-text-tertiary);
    cursor: default;
  }
</style>

// frontend-replit/artifacts/svvy/src/components/svvy/WaitingCard.tsx
import { useState } from "react";
import { cn } from "@/lib/utils";
import { Clock } from "lucide-react";

interface WaitingCardProps {
  question: string;
  context?: string;
  className?: string;
  onReply?: (text: string) => void;
}

export function WaitingCard({ question, context, className, onReply }: WaitingCardProps) {
  const [reply, setReply] = useState("");

  return (
    <div
      className={cn(
        "border border-border rounded bg-card border-l-2 border-l-amber-500",
        className
      )}
      data-testid="waiting-card"
    >
      <div className="flex items-center gap-2 px-3 py-2 border-b border-border">
        <span className="w-2 h-2 rounded-full bg-amber-500 pulse-dot" />
        <Clock className="w-3.5 h-3.5 text-amber-400" />
        <span className="text-[12px] font-medium text-amber-400">Waiting for input</span>
      </div>

      <div className="px-3 py-2.5">
        {context && (
          <p className="text-[11px] text-muted-foreground mb-2 leading-relaxed">{context}</p>
        )}
        <p className="text-[13px] text-foreground leading-relaxed mb-3">{question}</p>

        <div className="flex items-center gap-2">
          <input
            type="text"
            value={reply}
            onChange={e => setReply(e.target.value)}
            placeholder="Type your response..."
            className="flex-1 text-[12px] bg-muted border border-border rounded px-2.5 py-1.5 text-foreground placeholder:text-muted-foreground outline-none focus:border-ring transition-colors"
            data-testid="waiting-reply-input"
            onKeyDown={e => {
              if (e.key === "Enter" && reply.trim() && onReply) {
                onReply(reply);
                setReply("");
              }
            }}
          />
          <button
            onClick={() => { if (reply.trim() && onReply) { onReply(reply); setReply(""); } }}
            disabled={!reply.trim()}
            className={cn(
              "text-[11px] px-3 py-1.5 rounded font-medium transition-colors",
              reply.trim()
                ? "bg-orange-500 text-white hover:bg-orange-600"
                : "bg-muted text-muted-foreground cursor-not-allowed"
            )}
            data-testid="btn-reply"
          >
            Reply
          </button>
        </div>

        <button className="text-[10px] text-muted-foreground hover:text-foreground transition-colors mt-2 block">
          Skip and continue
        </button>
      </div>
    </div>
  );
}
