// src/mainview/WorkflowGraph.svelte
<script lang="ts">
  import BotIcon from "@lucide/svelte/icons/bot";
  import CheckCircle2Icon from "@lucide/svelte/icons/check-circle-2";
  import ClockIcon from "@lucide/svelte/icons/clock";
  import FlagIcon from "@lucide/svelte/icons/flag";
  import GitBranchIcon from "@lucide/svelte/icons/git-branch";
  import RefreshCwIcon from "@lucide/svelte/icons/refresh-cw";
  import ShieldIcon from "@lucide/svelte/icons/shield";
  import TerminalIcon from "@lucide/svelte/icons/terminal";
  import ZapIcon from "@lucide/svelte/icons/zap";
  import type { WorkspaceWorkflowInspectorNode } from "../shared/workspace-contract";

  type Props = {
    nodes: WorkspaceWorkflowInspectorNode[];
    selectedNodeKey: string | null;
    onSelect: (key: string) => void;
  };

  type PositionedNode = WorkspaceWorkflowInspectorNode & {
    x: number;
    y: number;
  };

  const NODE_W = 150;
  const NODE_H = 52;
  const COLUMN_GAP = 62;
  const ROW_GAP = 42;

  let { nodes, selectedNodeKey, onSelect }: Props = $props();

  const positionedNodes = $derived.by(() => layoutNodes(nodes));
  const graphWidth = $derived(Math.max(420, ...positionedNodes.map((node) => node.x + NODE_W + 24)));
  const graphHeight = $derived(Math.max(260, ...positionedNodes.map((node) => node.y + NODE_H + 24)));
  const nodeByKey = $derived(new Map(positionedNodes.map((node) => [node.key, node])));
  const edges = $derived(
    positionedNodes
      .map((node) => {
        const parent = node.parentKey ? nodeByKey.get(node.parentKey) : null;
        return parent ? { from: parent, to: node } : null;
      })
      .filter((edge): edge is { from: PositionedNode; to: PositionedNode } => Boolean(edge)),
  );

  function layoutNodes(input: WorkspaceWorkflowInspectorNode[]): PositionedNode[] {
    const childrenByParent = new Map<string | null, WorkspaceWorkflowInspectorNode[]>();
    for (const node of input) {
      const siblings = childrenByParent.get(node.parentKey) ?? [];
      siblings.push(node);
      childrenByParent.set(node.parentKey, siblings);
    }

    const positioned = new Map<string, PositionedNode>();
    let nextRow = 0;

    function place(node: WorkspaceWorkflowInspectorNode, depth: number): number {
      const children = childrenByParent.get(node.key) ?? [];
      const childRows = children.map((child) => place(child, depth + 1));
      const row = childRows.length
        ? (Math.min(...childRows) + Math.max(...childRows)) / 2
        : nextRow++;
      positioned.set(node.key, {
        ...node,
        x: 18 + depth * (NODE_W + COLUMN_GAP),
        y: 18 + row * (NODE_H + ROW_GAP),
      });
      return row;
    }

    const roots = childrenByParent.get(null) ?? input.filter((node) => !node.parentKey);
    for (const root of roots) place(root, 0);

    return input.map((node) => positioned.get(node.key)).filter((node): node is PositionedNode => Boolean(node));
  }

  function typeLabel(type: WorkspaceWorkflowInspectorNode["type"]): string {
    if (type === "task-agent") return "agent";
    if (type === "project-ci-check") return "verify";
    if (type === "terminal-result") return "terminal";
    return type.replace(/-/g, " ");
  }

  function formatElapsed(ms: number | null): string | null {
    if (ms == null) return null;
    if (ms < 1000) return `${ms}ms`;
    const seconds = Math.round(ms / 1000);
    if (seconds < 60) return `${seconds}s`;
    const minutes = Math.floor(seconds / 60);
    return `${minutes}m ${seconds % 60}s`;
  }

  function edgeClass(status: WorkspaceWorkflowInspectorNode["status"]): string {
    if (status === "completed") return "done";
    if (status === "running" || status === "retrying") return "active";
    if (status === "failed" || status === "cancelled") return "failed";
    if (status === "waiting") return "waiting";
    return "pending";
  }
</script>

<div class="workflow-graph" data-testid="workflow-graph">
  <div class="workflow-graph-canvas">
    <div class="workflow-graph-inner" style={`width: ${graphWidth}px; height: ${graphHeight}px`}>
      <svg class="workflow-graph-edges" width={graphWidth} height={graphHeight} aria-hidden="true">
        {#each edges as edge (`${edge.from.key}-${edge.to.key}`)}
          {@const x1 = edge.from.x + NODE_W / 2}
          {@const y1 = edge.from.y + NODE_H}
          {@const x2 = edge.to.x + NODE_W / 2}
          {@const y2 = edge.to.y}
          {@const curve = Math.max(34, Math.abs(y2 - y1) * 0.45)}
          <path
            class={`workflow-edge ${edgeClass(edge.from.status)}`}
            d={`M ${x1} ${y1} C ${x1} ${y1 + curve}, ${x2} ${y2 - curve}, ${x2} ${y2}`}
          />
        {/each}
      </svg>

      {#each positionedNodes as node (node.key)}
        {@const elapsed = formatElapsed(node.timing.elapsedMs)}
        <button
          type="button"
          class={`workflow-graph-node type-${node.type} status-${node.status} ${node.key === selectedNodeKey ? "selected" : ""}`.trim()}
          style={`left: ${node.x}px; top: ${node.y}px; width: ${NODE_W}px; height: ${NODE_H}px`}
          aria-pressed={node.key === selectedNodeKey}
          onclick={() => onSelect(node.key)}
        >
          <span class="workflow-graph-icon" aria-hidden="true">
            {#if node.type === "task-agent"}
              <BotIcon size={14} />
            {:else if node.type === "script"}
              <TerminalIcon size={14} />
            {:else if node.type === "project-ci-check"}
              <CheckCircle2Icon size={14} />
            {:else if node.type === "wait" || node.type === "approval"}
              <ClockIcon size={14} />
            {:else if node.type === "retry"}
              <RefreshCwIcon size={14} />
            {:else if node.type === "terminal-result"}
              <FlagIcon size={14} />
            {:else if node.type === "conditional"}
              <GitBranchIcon size={14} />
            {:else if node.type === "workflow"}
              <ShieldIcon size={14} />
            {:else}
              <ZapIcon size={14} />
            {/if}
          </span>
          <span class="workflow-graph-node-copy">
            <span class="workflow-graph-label">{node.label}</span>
            <span class="workflow-graph-status">
              {#if node.status === "running" || node.status === "retrying"}
                <span class="workflow-graph-pulse" aria-hidden="true"></span>
              {/if}
              {node.status}
            </span>
          </span>
          {#if elapsed}
            <span class="workflow-graph-elapsed">{elapsed}</span>
          {/if}
          <span class="workflow-graph-type">{typeLabel(node.type)}</span>
        </button>
      {/each}
    </div>
  </div>
</div>

<style>
  .workflow-graph {
    min-height: 0;
    height: 100%;
    background:
      linear-gradient(color-mix(in oklab, var(--ui-border-soft) 18%, transparent) 1px, transparent 1px),
      linear-gradient(90deg, color-mix(in oklab, var(--ui-border-soft) 18%, transparent) 1px, transparent 1px),
      color-mix(in oklab, var(--ui-surface) 94%, var(--ui-surface-subtle));
    background-size: 24px 24px;
  }

  .workflow-graph-canvas {
    min-height: 0;
    height: 100%;
    overflow: auto;
    padding: 0.85rem;
  }

  .workflow-graph-inner {
    position: relative;
  }

  .workflow-graph-edges {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }

  .workflow-edge {
    fill: none;
    stroke: color-mix(in oklab, var(--ui-text-tertiary) 28%, transparent);
    stroke-width: 1.4;
  }

  .workflow-edge.done {
    stroke: color-mix(in oklab, var(--ui-success) 50%, transparent);
  }

  .workflow-edge.active {
    stroke: color-mix(in oklab, var(--ui-warning) 58%, transparent);
  }

  .workflow-edge.failed {
    stroke: color-mix(in oklab, var(--ui-danger) 54%, transparent);
  }

  .workflow-edge.waiting {
    stroke-dasharray: 4 4;
  }

  .workflow-graph-node {
    position: absolute;
    display: grid;
    grid-template-columns: auto minmax(0, 1fr) auto;
    grid-template-rows: minmax(0, 1fr) auto;
    align-items: center;
    gap: 0.12rem 0.45rem;
    padding: 0.42rem 0.52rem;
    border: 1px solid color-mix(in oklab, var(--ui-border-soft) 90%, transparent);
    border-radius: var(--ui-radius-sm);
    background: color-mix(in oklab, var(--ui-surface-raised) 82%, transparent);
    color: var(--ui-text-primary);
    cursor: pointer;
    text-align: left;
    transition:
      border-color 140ms cubic-bezier(0.19, 1, 0.22, 1),
      background-color 140ms cubic-bezier(0.19, 1, 0.22, 1),
      transform 140ms cubic-bezier(0.19, 1, 0.22, 1);
  }

  .workflow-graph-node:hover,
  .workflow-graph-node.selected {
    border-color: color-mix(in oklab, var(--ui-border-accent) 72%, var(--ui-border-soft));
    background: color-mix(in oklab, var(--ui-surface-raised) 94%, var(--ui-accent-soft));
  }

  .workflow-graph-node:hover {
    transform: translateY(-1px);
  }

  .workflow-graph-node.selected {
    box-shadow:
      0 0 0 1px color-mix(in oklab, var(--ui-border-accent) 44%, transparent),
      0 10px 24px hsl(0 0% 0% / 0.22);
  }

  .workflow-graph-icon {
    grid-row: 1;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 1.35rem;
    height: 1.35rem;
    color: var(--ui-text-secondary);
  }

  .workflow-graph-node-copy {
    min-width: 0;
  }

  .workflow-graph-label {
    display: block;
    overflow: hidden;
    color: var(--ui-text-primary);
    font-family: var(--font-mono);
    font-size: 0.68rem;
    line-height: 1.18;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .workflow-graph-status,
  .workflow-graph-elapsed,
  .workflow-graph-type {
    color: var(--ui-text-tertiary);
    font-family: var(--font-mono);
    font-size: 0.56rem;
    line-height: 1;
    text-transform: uppercase;
  }

  .workflow-graph-status {
    display: inline-flex;
    align-items: center;
    gap: 0.25rem;
    margin-top: 0.24rem;
  }

  .workflow-graph-elapsed {
    justify-self: end;
    text-transform: none;
  }

  .workflow-graph-type {
    grid-column: 1 / -1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .workflow-graph-pulse {
    width: 0.32rem;
    height: 0.32rem;
    border-radius: 999px;
    background: var(--ui-warning);
    animation: workflow-graph-pulse 1.35s ease-in-out infinite;
  }

  .status-completed {
    border-color: color-mix(in oklab, var(--ui-success) 36%, var(--ui-border-soft));
  }

  .status-running,
  .status-retrying {
    border-color: color-mix(in oklab, var(--ui-warning) 58%, var(--ui-border-soft));
  }

  .status-failed,
  .status-cancelled {
    border-color: color-mix(in oklab, var(--ui-danger) 58%, var(--ui-border-soft));
  }

  .status-waiting {
    opacity: 0.72;
  }

  .type-task-agent .workflow-graph-icon {
    color: color-mix(in oklab, var(--ui-info) 72%, var(--ui-text-primary));
  }

  .type-script .workflow-graph-icon {
    color: color-mix(in oklab, var(--ui-accent) 70%, var(--ui-text-primary));
  }

  .type-project-ci-check .workflow-graph-icon,
  .type-terminal-result .workflow-graph-icon {
    color: color-mix(in oklab, var(--ui-success) 74%, var(--ui-text-primary));
  }

  .type-wait .workflow-graph-icon,
  .type-approval .workflow-graph-icon,
  .type-retry .workflow-graph-icon {
    color: color-mix(in oklab, var(--ui-warning) 76%, var(--ui-text-primary));
  }

  @keyframes workflow-graph-pulse {
    0%,
    100% {
      box-shadow: 0 0 0 0 color-mix(in oklab, var(--ui-warning) 38%, transparent);
    }
    50% {
      box-shadow: 0 0 0 0.26rem color-mix(in oklab, var(--ui-warning) 0%, transparent);
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .workflow-graph-node {
      transition: none;
    }

    .workflow-graph-node:hover {
      transform: none;
    }

    .workflow-graph-pulse {
      animation: none;
    }
  }
</style>

// frontend-replit/artifacts/svvy/src/components/svvy/WorkflowGraph.tsx
import { useState } from "react";
import { cn } from "@/lib/utils";
import { Bot, Terminal, CheckCircle2, Clock, RefreshCw, Flag, Shield, Zap } from "lucide-react";
import { ModelBadge } from "./ModelBadge";
import { ArtifactChip } from "./ArtifactChip";
import type { WorkflowNode, WorkflowEdge, NodeType, NodeStatus } from "@/data/mock";

interface WorkflowGraphProps {
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
}

const nodeTypeConfig: Record<
  NodeType,
  {
    icon: React.ElementType;
    border: string;
    bg: string;
    label: string;
  }
> = {
  "agent-task": { icon: Bot, border: "border-blue-500/40", bg: "bg-blue-500/8", label: "agent" },
  script: {
    icon: Terminal,
    border: "border-purple-500/40",
    bg: "bg-purple-500/8",
    label: "script",
  },
  verification: {
    icon: CheckCircle2,
    border: "border-emerald-500/40",
    bg: "bg-emerald-500/8",
    label: "verify",
  },
  wait: { icon: Clock, border: "border-amber-500/40", bg: "bg-amber-500/8", label: "wait" },
  retry: { icon: RefreshCw, border: "border-orange-500/40", bg: "bg-orange-500/8", label: "retry" },
  terminal: { icon: Flag, border: "border-slate-500/40", bg: "bg-slate-500/8", label: "terminal" },
  preflight: { icon: Shield, border: "border-sky-500/40", bg: "bg-sky-500/8", label: "preflight" },
  validation: { icon: Zap, border: "border-teal-500/40", bg: "bg-teal-500/8", label: "validate" },
};

const nodeStatusBorder: Record<NodeStatus, string> = {
  active: "border-orange-500",
  completed: "border-emerald-500/50",
  failed: "border-red-500",
  waiting: "border-muted-foreground/20",
};

const nodeStatusGlow: Record<NodeStatus, string> = {
  active: "shadow-[0_0_8px_rgba(249,115,22,0.3)]",
  completed: "",
  failed: "shadow-[0_0_8px_rgba(239,68,68,0.25)]",
  waiting: "",
};

const NODE_W = 130;
const NODE_H = 44;

export function WorkflowGraph({ nodes, edges }: WorkflowGraphProps) {
  const [selectedNode, setSelectedNode] = useState<WorkflowNode | null>(null);

  const graphHeight = Math.max(...nodes.map((n) => n.y)) + NODE_H + 20;
  const graphWidth = Math.max(...nodes.map((n) => n.x)) + NODE_W + 20;

  return (
    <div className="flex flex-col h-full" data-testid="workflow-graph">
      {/* Graph area */}
      <div className="flex-1 overflow-auto scrollbar-thin p-4 min-h-0">
        <div className="relative" style={{ width: graphWidth, height: graphHeight }}>
          {/* SVG edges */}
          <svg
            className="absolute inset-0 pointer-events-none"
            width={graphWidth}
            height={graphHeight}
          >
            {edges.map((edge, i) => {
              const from = nodes.find((n) => n.id === edge.from);
              const to = nodes.find((n) => n.id === edge.to);
              if (!from || !to) return null;

              const x1 = from.x + NODE_W / 2;
              const y1 = from.y + NODE_H;
              const x2 = to.x + NODE_W / 2;
              const y2 = to.y;

              const cy1 = y1 + Math.abs(y2 - y1) * 0.5;
              const cy2 = y2 - Math.abs(y2 - y1) * 0.5;

              const fromNode = from;
              const isDone = fromNode.status === "completed";
              const isActive = fromNode.status === "active";

              return (
                <path
                  key={i}
                  d={`M ${x1} ${y1} C ${x1} ${cy1}, ${x2} ${cy2}, ${x2} ${y2}`}
                  fill="none"
                  stroke={
                    isDone
                      ? "rgba(34,197,94,0.4)"
                      : isActive
                        ? "rgba(249,115,22,0.5)"
                        : "rgba(255,255,255,0.08)"
                  }
                  strokeWidth="1.5"
                  strokeDasharray={fromNode.status === "waiting" ? "4 3" : undefined}
                />
              );
            })}

            {/* Arrowheads */}
            <defs>
              <marker
                id="arrow-done"
                markerWidth="6"
                markerHeight="6"
                refX="3"
                refY="3"
                orient="auto"
              >
                <path d="M 0 0 L 6 3 L 0 6 Z" fill="rgba(34,197,94,0.5)" />
              </marker>
              <marker
                id="arrow-pending"
                markerWidth="6"
                markerHeight="6"
                refX="3"
                refY="3"
                orient="auto"
              >
                <path d="M 0 0 L 6 3 L 0 6 Z" fill="rgba(255,255,255,0.12)" />
              </marker>
            </defs>
          </svg>

          {/* Nodes */}
          {nodes.map((node) => {
            const config = nodeTypeConfig[node.type] || nodeTypeConfig["agent-task"];
            const Icon = config.icon;
            const isSelected = selectedNode?.id === node.id;

            return (
              <button
                key={node.id}
                onClick={() => setSelectedNode(isSelected ? null : node)}
                style={{ left: node.x, top: node.y, width: NODE_W, height: NODE_H }}
                className={cn(
                  "absolute border rounded flex items-center gap-2 px-2.5 text-left transition-all duration-150",
                  config.border,
                  config.bg,
                  nodeStatusBorder[node.status],
                  nodeStatusGlow[node.status],
                  isSelected && "ring-1 ring-ring ring-offset-0",
                  "hover:brightness-110",
                  node.status === "waiting" && "opacity-50",
                )}
                data-testid={`workflow-node-${node.id}`}
              >
                <Icon
                  className={cn(
                    "w-3 h-3 flex-shrink-0",
                    node.status === "completed" && "text-emerald-500",
                    node.status === "active" && "text-orange-500",
                    node.status === "failed" && "text-red-500",
                    node.status === "waiting" && "text-muted-foreground",
                  )}
                />
                <div className="min-w-0">
                  <div className="text-[10px] font-mono text-foreground/90 truncate leading-tight">
                    {node.label}
                  </div>
                  <div
                    className={cn(
                      "text-[9px] font-mono uppercase tracking-wide",
                      node.status === "completed" && "text-emerald-500",
                      node.status === "active" && "text-orange-400",
                      node.status === "failed" && "text-red-400",
                      node.status === "waiting" && "text-muted-foreground/60",
                    )}
                  >
                    {node.status === "active" && (
                      <span className="inline-flex items-center gap-1">
                        <span className="w-1 h-1 rounded-full bg-orange-500 pulse-dot" />
                        {node.status}
                      </span>
                    )}
                    {node.status !== "active" && node.status}
                  </div>
                </div>
                {node.elapsed && (
                  <span className="font-mono text-[8px] text-muted-foreground ml-auto flex-shrink-0">
                    {node.elapsed}
                  </span>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Node detail panel */}
      {selectedNode && (
        <div className="border-t border-border bg-card flex-shrink-0 px-4 py-3 space-y-2.5 max-h-56 overflow-y-auto scrollbar-thin">
          <div className="flex items-start justify-between gap-2">
            <div>
              <span className="font-mono text-[11px] text-foreground/90">{selectedNode.label}</span>
              <span
                className={cn(
                  "ml-2 font-mono text-[9px] uppercase px-1.5 py-0.5 rounded border",
                  nodeTypeConfig[selectedNode.type]?.border,
                  nodeTypeConfig[selectedNode.type]?.bg,
                  "text-muted-foreground",
                )}
              >
                {nodeTypeConfig[selectedNode.type]?.label}
              </span>
            </div>
            <button
              onClick={() => setSelectedNode(null)}
              className="text-muted-foreground hover:text-foreground text-lg leading-none"
            >
              ×
            </button>
          </div>

          {selectedNode.objective && (
            <p className="text-[12px] text-foreground/80 leading-relaxed">
              {selectedNode.objective}
            </p>
          )}

          {selectedNode.latestOutput && (
            <div>
              <div className="text-[9px] font-mono text-muted-foreground uppercase tracking-wider mb-1">
                Latest output
              </div>
              <div className="bg-muted/40 rounded border border-border px-2.5 py-2 text-[11px] font-mono text-foreground/80 leading-relaxed">
                {selectedNode.latestOutput}
              </div>
            </div>
          )}

          <div className="flex items-center gap-4 flex-wrap">
            {selectedNode.elapsed && (
              <div className="flex items-center gap-1">
                <span className="text-[10px] text-muted-foreground">Elapsed</span>
                <span className="font-mono text-[10px] text-foreground/70">
                  {selectedNode.elapsed}
                </span>
              </div>
            )}
            {selectedNode.model && (
              <div className="flex items-center gap-1">
                <span className="text-[10px] text-muted-foreground">Model</span>
                <ModelBadge model={selectedNode.model} size="xs" />
              </div>
            )}
            {selectedNode.worktree && (
              <div className="flex items-center gap-1">
                <span className="text-[10px] text-muted-foreground">Worktree</span>
                <span className="font-mono text-[10px] text-foreground/70">
                  {selectedNode.worktree}
                </span>
              </div>
            )}
          </div>

          {selectedNode.artifacts && selectedNode.artifacts.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {selectedNode.artifacts.map((a) => (
                <ArtifactChip key={a.id} name={a.name} type={a.type} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
